### ISSUE TITLE
vervison under 4.6.0 is unavailable in https://dist.apache.org/repos/dist/release/rocketmq

### ISSUE THREAD

**Issue by ouyangxuanyun** [apache/rocketmq-docker#14]
rocketmq-docker/image-build/Dockerfile-centos
Line: 50-51

> https://dist.apache.org/repos/dist/release/rocketmq/${ROCKETMQ_VERSION}/rocketmq-all-${ROCKETMQ_VERSION}-bin-release.zip

should be replaced by 

> https://archive.apache.org/dist/rocketmq/${ROCKETMQ_VERSION}/rocketmq-all-${ROCKETMQ_VERSION}-source-release.zip

**Comment by ShannonDing** [comment]
Hello,
You are right.
As ASF required, the old release should be moved to archive service and removed from mirrors.
The latest release package can be found both in the apache dist and apache archive server.
we can still download the older releases if necessary, but the links should point to the archive server.
In order to keep the Dockerfile always to work fine, it is better to change the package download link to the apache archive server.

**Comment by ShannonDing** [comment]
link #15

**Comment by ShannonDing** [comment]
@ouyangxuanyun Could you please have a test on PR #16?
